import {Publisher} from './publisher';



export const PUBLISHERS: Publisher[] = [
  {id: 1, name: 'Heinemann', mail: 'another@mail.com', city: 'city', state: 'st', country: 'country'},
  {id: 2, name: 'Grand Central Publishing', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 3, name: 'Houghton Mifflin Harcourt', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 4, name: 'Hachette Audio', mail: 'another@mail.com', city: 'city', state: 'st', country: 'FR'},
  {id: 5, name: 'Dover Publications', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 6, name: 'Norton, W. W. & Company, Inc.', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 7, name: 'Simon & Schuster Adult Publishing Group', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 8, name: 'Oxford University Press, USA', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 12, name: 'HarperCollins Publishers', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 15, name: 'Penguin Group (USA)', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 19, name: 'Knopf Doubleday Publishing Group', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 23, name: 'Bedford\/St. Martin\'s', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 26, name: 'Applause Theatre Book Publishers', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 28, name: 'Paperback', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 30, name: 'Longman', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 32, name: 'Library of America', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 35, name: 'Prentice Hall', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 36, name: 'Cengage Learning', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 42, name: 'University of Georgia Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 45, name: ' Rosencrantz and Guildenstern are Dead', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 49, name: 'Cider Mill Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 52, name: 'Simon & Schuster Children\'s Publishing', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 57, name: 'Houghton Mifflin Company', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 60, name: 'Arte Publico Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 61, name: 'Cambridge University Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 62, name: 'Dramatists Play Service, Incorporated', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 63, name: 'McGraw-Hill Companies, The', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 66, name: 'Crown Publishing Group', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 67, name: 'Basic Books', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 68, name: 'Atlas & Co.', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 70, name: 'Random House Publishing Group', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 71, name: 'Milkweed Editions', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 74, name: 'South End Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 75, name: 'Smith, Gibbs Publisher', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 76, name: 'Augsburg Fortress, Publishers', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 78, name: 'Columbia University Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 89, name: 'Padma Publishing', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 91, name: 'New York University Press', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'},
  {id: 96, name: 'Rivergate Books', mail: 'another@mail.com', city: 'city', state: 'st', country: 'USA'}
];
